### ISSUE TITLE
simpler (?) code for computing many segregation indices

### ISSUE THREAD

**Issue by elbersb** [walkerke/census-with-r-book#1]
Hi Kyle,
here's a small suggestion for 8.1. 

Instead of 

```r
ca_urban_data %>%
  split(~urban_name) %>%
  imap_dfr(~{
    .x %>%
      filter(variable %in% c("white", "hispanic")) %>%
      dissimilarity(
        group = "variable",
        unit = "GEOID",
        weight = "estimate"
      )
  }, .id = "urban_name") %>%
  arrange(desc(est))
```

I'd propose

```r
ca_urban_data %>%
  filter(variable %in% c("white", "hispanic")) %>%
  group_by(urban_name) %>%
  group_modify(~
      dissimilarity(.x,
        group = "variable",
        unit = "GEOID",
        weight = "estimate"
      )) %>% 
  arrange(desc(est))
```

This doesn't require mixing Base R (`split`) and tidyverse, and I find it more naturally that the operation is done on the grouped data frame. It's really only stylistic though, so feel free to close.

**Comment by walkerke** [comment]
Thanks @elbersb!  I do like this better and I had a version of this in draft after I read your blog post (I'd never used `group_modify()`!).  I'll need to change the text a bit around the example too but I'm planning to include this in the next batch of updates.

**Comment by walkerke** [comment]
This is now implemented.  Thanks @elbersb!
